Repository EFUB5-RoomListener/MAVVE-back, pull requests merged in 2025-07, with the labels that each got.

#2 [Chore] 프로젝트 기본 세팅
  mavve/.gitattributes
  mavve/.gitignore
  mavve/build.gradle
  mavve/gradle/wrapper/gradle-wrapper.jar
  mavve/gradle/wrapper/gradle-wrapper.properties
  mavve/gradlew
  mavve/gradlew.bat
  mavve/settings.gradle
  mavve/src/main/java/com/efub/mavve/MavveApplication.java
  mavve/src/main/java/com/efub/mavve/global/config/CorsConfig.java
  mavve/src/main/java/com/efub/mavve/global/config/SecurityConfig.java
  mavve/src/main/resources/application.yml
  mavve/src/test/java/com/efub/mavve/MavveApplicationTests.java
Labels: Chore

#4 [Feat] 에러 핸들러 구성 #3
  mavve/src/main/java/com/efub/mavve/global/exception/ClientExceptionCode.java
  mavve/src/main/java/com/efub/mavve/global/exception/ExceptionCode.java
  mavve/src/main/java/com/efub/mavve/global/exception/MavveException.java
  mavve/src/main/java/com/efub/mavve/global/exception/dto/ExceptionResponse.java
  mavve/src/main/java/com/efub/mavve/global/handler/GlobalErrorHandler.java
Labels: Feature

#14 [Feat] S3 연결 및 이미지 업로드/삭제
  mavve/build.gradle
  mavve/src/main/java/com/efub/mavve/global/S3Image/S3ImageService.java
  mavve/src/main/java/com/efub/mavve/global/config/S3Config.java
  mavve/src/main/java/com/efub/mavve/global/config/YoutubeConfig.java
  mavve/src/main/java/com/efub/mavve/global/exception/ClientExceptionCode.java
  mavve/src/main/java/com/efub/mavve/global/exception/ExceptionCode.java
  mavve/src/main/java/com/efub/mavve/global/youtube/YoutubeService.java
  mavve/src/main/resources/application.yml
Labels: Feature

#15 [Feat] reissue API 구현 #8
  mavve/src/main/java/com/efub/mavve/auth/controller/AuthController.java
  mavve/src/main/java/com/efub/mavve/auth/dto/request/KakaoCodeRequest.java
  mavve/src/main/java/com/efub/mavve/auth/repository/UserRepository.java
  mavve/src/main/java/com/efub/mavve/auth/service/AuthService.java
  mavve/src/main/java/com/efub/mavve/global/config/RedisConfig.java
Labels: Feature

#21 [Feat] Spotify login api
  mavve/src/main/java/com/efub/mavve/auth/controller/AuthController.java
  mavve/src/main/java/com/efub/mavve/auth/domain/User.java
  mavve/src/main/java/com/efub/mavve/auth/dto/request/SpotifyCodeRequest.java
  mavve/src/main/java/com/efub/mavve/auth/dto/response/KakaoAccountResponse.java
  mavve/src/main/java/com/efub/mavve/auth/dto/response/KakaoProfileResponse.java
  mavve/src/main/java/com/efub/mavve/auth/dto/response/KakaoTokenResponse.java
  mavve/src/main/java/com/efub/mavve/auth/dto/response/KakaoUserInfoResponse.java
  mavve/src/main/java/com/efub/mavve/auth/dto/response/SpotifyRedirctUri.java
  mavve/src/main/java/com/efub/mavve/auth/dto/response/SpotifyTokenResponse.java
  mavve/src/main/java/com/efub/mavve/auth/dto/response/SpotifyUserInfoRaw.java
  mavve/src/main/java/com/efub/mavve/auth/dto/response/SpotifyUserInfoResponse.java
  mavve/src/main/java/com/efub/mavve/auth/repository/UserRepository.java
  mavve/src/main/java/com/efub/mavve/auth/service/AuthService.java
  mavve/src/main/java/com/efub/mavve/auth/service/jwt/SpotifyTokenService.java
  mavve/src/main/java/com/efub/mavve/auth/service/oauth/OauthClient.java
  mavve/src/main/java/com/efub/mavve/auth/service/oauth/OauthProperties.java
  mavve/src/main/resources/application.yml
Labels: Feature

#17 [Feat] 플레이리스트 CRUD 구현
  mavve/src/main/java/com/efub/mavve/playlist/controller/PlaylistController.java
  mavve/src/main/java/com/efub/mavve/playlist/domain/Playlist.java
  mavve/src/main/java/com/efub/mavve/playlist/dto/request/PlaylistCreateRequest.java
  mavve/src/main/java/com/efub/mavve/playlist/dto/request/PlaylistUpdateRequest.java
  mavve/src/main/java/com/efub/mavve/playlist/dto/response/PlaylistListResponse.java
  mavve/src/main/java/com/efub/mavve/playlist/dto/response/PlaylistResponse.java
  mavve/src/main/java/com/efub/mavve/playlist/dto/summary/PlaylistSummary.java
  mavve/src/main/java/com/efub/mavve/playlist/repository/PlaylistRepository.java
  mavve/src/main/java/com/efub/mavve/playlist/service/PlaylistService.java
Labels: Feature

#25 [Feat] 유저프로필 가져오기 및 수정 api
  mavve/src/main/java/com/efub/mavve/auth/controller/AuthController.java
  mavve/src/main/java/com/efub/mavve/auth/domain/User.java
  mavve/src/main/java/com/efub/mavve/auth/dto/request/UserInfoRequest.java
  mavve/src/main/java/com/efub/mavve/auth/dto/response/UserInfoResponse.java
  mavve/src/main/java/com/efub/mavve/auth/service/AuthService.java
  mavve/src/main/java/com/efub/mavve/songs/controller/SongController.java
Labels: Feature

#35 [Feat] image 업로드/삭제 controller 구현
  mavve/src/main/java/com/efub/mavve/global/S3Image/controller/S3ImageController.java
  mavve/src/main/java/com/efub/mavve/global/S3Image/dto/request/ImageDeleteRequest.java
  mavve/src/main/java/com/efub/mavve/global/S3Image/dto/response/ImageUrlResponse.java
  mavve/src/main/java/com/efub/mavve/global/S3Image/service/S3ImageService.java
Labels: Feature

#42 [Feat] 한 줄 일기 CRUD api
  mavve/src/main/java/com/efub/mavve/diary/controller/DiaryController.java
  mavve/src/main/java/com/efub/mavve/diary/domain/Diary.java
  mavve/src/main/java/com/efub/mavve/diary/domain/Emoji.java
  mavve/src/main/java/com/efub/mavve/diary/dto/request/DiaryCreateRequest.java
  mavve/src/main/java/com/efub/mavve/diary/dto/request/DiaryUpdateRequest.java
  mavve/src/main/java/com/efub/mavve/diary/dto/response/DiaryListResponse.java
  mavve/src/main/java/com/efub/mavve/diary/dto/response/DiaryResponse.java
  mavve/src/main/java/com/efub/mavve/diary/repository/DiaryRepository.java
  mavve/src/main/java/com/efub/mavve/diary/repository/EmojiRepository.java
  mavve/src/main/java/com/efub/mavve/diary/service/DiaryService.java
  mavve/src/main/java/com/efub/mavve/global/exception/ClientExceptionCode.java
  mavve/src/main/java/com/efub/mavve/global/exception/ExceptionCode.java
  mavve/src/main/java/com/efub/mavve/room/controller/RoomController.java
  mavve/src/main/java/com/efub/mavve/room/domain/Room.java
  mavve/src/main/java/com/efub/mavve/room/dto/projection/RoomLikeCountProjection.java
  mavve/src/main/java/com/efub/mavve/room/dto/request/RoomUpdateRequest.java
  mavve/src/main/java/com/efub/mavve/room/dto/response/RoomResponse.java
  mavve/src/main/java/com/efub/mavve/room/repository/RoomRepository.java
  mavve/src/main/java/com/efub/mavve/room/service/RoomService.java
  mavve/src/main/java/com/efub/mavve/songs/repository/SongArtistRepository.java
Labels: Feature

#45 [Feat] 방 입장 시 정보 전달/웹소켓 연결 및 웹소켓 종료 이벤트 처리
  mavve/src/main/java/com/efub/mavve/global/config/RedisConfig.java
  mavve/src/main/java/com/efub/mavve/global/config/WebSocketConfig.java
  mavve/src/main/java/com/efub/mavve/global/exception/ClientExceptionCode.java
  mavve/src/main/java/com/efub/mavve/global/exception/ExceptionCode.java
  mavve/src/main/java/com/efub/mavve/global/handler/StompHandler.java
  mavve/src/main/java/com/efub/mavve/global/handler/WebSocketEventListener.java
  mavve/src/main/java/com/efub/mavve/room/controller/RoomController.java
  mavve/src/main/java/com/efub/mavve/room/controller/websocket/RoomSongWebsocketController.java
  mavve/src/main/java/com/efub/mavve/room/controller/websocket/RoomWebsocketController.java
  mavve/src/main/java/com/efub/mavve/room/dto/response/RoomEnterResponse.java
  mavve/src/main/java/com/efub/mavve/room/payload/response/MessageType.java
  mavve/src/main/java/com/efub/mavve/room/payload/response/SubscribeResponsePayload.java
  mavve/src/main/java/com/efub/mavve/room/payload/summary/CurrentSongSummary.java
  mavve/src/main/java/com/efub/mavve/room/service/RoomChatService.java
  mavve/src/main/java/com/efub/mavve/room/service/RoomService.java
  mavve/src/main/java/com/efub/mavve/room/service/redis/RedisStartCleaner.java
  mavve/src/main/java/com/efub/mavve/room/service/redis/RoomRedisKeyUtils.java
  mavve/src/main/java/com/efub/mavve/room/service/redis/RoomSongRedisService.java
  mavve/src/main/java/com/efub/mavve/room/service/redis/RoomUserRedisService.java
  mavve/src/main/java/com/efub/mavve/room/service/websocket/PrincipalUtil.java
  mavve/src/main/java/com/efub/mavve/room/service/websocket/RoomSongWebsocketService.java
Labels: Feature

#48 [Feat] 채팅 전체 조회
  mavve/src/main/java/com/efub/mavve/room/controller/RoomController.java
  mavve/src/main/java/com/efub/mavve/room/domain/RoomChat.java
  mavve/src/main/java/com/efub/mavve/room/dto/response/ChatListResponse.java
  mavve/src/main/java/com/efub/mavve/room/dto/summary/ChatSummary.java
  mavve/src/main/java/com/efub/mavve/room/repository/RoomChatRepository.java
  mavve/src/main/java/com/efub/mavve/room/service/RoomChatService.java
Labels: Feature

#64 [Feat] 방 새로 생성 시 노래 목록 redis에 저장
  mavve/src/main/java/com/efub/mavve/room/payload/summary/SongRedis.java
  mavve/src/main/java/com/efub/mavve/room/repository/RoomChatRepository.java
  mavve/src/main/java/com/efub/mavve/room/repository/RoomPlaylistRepository.java
  mavve/src/main/java/com/efub/mavve/room/service/RoomPlaylistService.java
  mavve/src/main/java/com/efub/mavve/room/service/RoomService.java
  mavve/src/main/java/com/efub/mavve/room/service/redis/RoomSongRedisService.java
  mavve/src/main/java/com/efub/mavve/room/service/websocket/RoomSongWebsocketService.java
Labels: Feature

#69 [Fix] diary response body 수정
  mavve/src/main/java/com/efub/mavve/diary/dto/response/DiaryResponse.java
Labels: Fix

#70 [Deploy] room 생성 API 에러 수정/ diary response body 수정
  mavve/src/main/java/com/efub/mavve/diary/dto/response/DiaryResponse.java
  mavve/src/main/java/com/efub/mavve/global/convertor/AttributeConverter.java
  mavve/src/main/java/com/efub/mavve/global/convertor/StringListConverter.java
  mavve/src/main/java/com/efub/mavve/room/domain/Room.java
Labels: Deploy

#75 [Fix] diary response body 수정 #41
  mavve/src/main/java/com/efub/mavve/diary/dto/response/DiaryResponse.java
Labels: Fix

#76 [Deploy] Diary Response Body 수정 배포
  mavve/src/main/java/com/efub/mavve/diary/dto/response/DiaryResponse.java
Labels: Deploy

#93 [Deploy] tag null 값일 때 빈 리스트 반환
  mavve/src/main/java/com/efub/mavve/global/convertor/StringListConverter.java
Labels: Deploy
